version: '3.8'

services:
  springdockerpj2:
    image: ${DOCKERHUB_USERNAME}/springdockerpj2:latest
    container_name: springdockerpj2
    restart: always
    ports:
      - "8095:8095"
    networks:
      - spring-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/backprojectdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy

networks:
  spring-network:
    name: spring-network
    external: true
volumes:
  mysql-data: